2019-03-15 14:06:08,927 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-15 14:06:08,935 - DEBUG - Using selector: EpollSelector
2019-03-15 14:07:24,448 - INFO - /home/admin/Documents/git/AMS-Project/src/handlers/filelogger.py modified; restarting server
2019-03-15 14:07:24,786 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-15 14:07:24,793 - DEBUG - Using selector: EpollSelector
2019-03-16 10:25:24,903 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 10:26:59,331 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 10:27:23,724 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 10:27:23,730 - DEBUG - Using selector: EpollSelector
2019-03-16 11:43:26,499 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 11:43:26,506 - DEBUG - Using selector: EpollSelector
2019-03-16 11:43:56,209 - INFO - 200 POST /api/view/ (::1) 6327.04ms
2019-03-16 11:45:18,299 - INFO - 200 GET /api/view/ (::1) 189.97ms
2019-03-16 11:45:42,667 - INFO - 200 POST /api/type/ (::1) 4019.53ms
2019-03-16 11:45:46,180 - INFO - 200 POST /api/type/ (::1) 1516.11ms
2019-03-16 11:45:51,934 - INFO - 200 GET /api/type/ (::1) 192.75ms
2019-03-16 11:46:19,027 - INFO - 200 POST /api/node/ (::1) 4209.13ms
2019-03-16 11:46:34,404 - INFO - 200 POST /api/node/ (::1) 1703.54ms
2019-03-16 11:46:48,249 - WARNING - 401 GET /api/node/ (::1) 0.38ms
2019-03-16 11:46:59,579 - INFO - 200 GET /api/node/ (::1) 193.99ms
2019-03-16 11:51:38,760 - ERROR - Uncaught exception POST /api/link/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/link/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/link.py", line 33, in post
    link_id = LinkUtil.create_link(link_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 33, in create_link
    if ViewUtil.view_id_exists(link_dict["view_id"]) == False:
KeyError: 'view_id'
2019-03-16 11:51:38,761 - ERROR - 500 POST /api/link/ (::1) 2997.85ms
2019-03-16 11:51:54,595 - WARNING - 401 GET /api/link/ (::1) 0.29ms
2019-03-16 11:52:06,638 - INFO - 200 GET /api/link/ (::1) 187.61ms
2019-03-16 11:53:42,008 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/link.py modified; restarting server
2019-03-16 11:53:42,234 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 11:53:42,239 - DEBUG - Using selector: EpollSelector
2019-03-16 11:53:56,193 - ERROR - Uncaught exception POST /api/link/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/link/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/link.py", line 39, in post
    LinkUtil.get_link_id(link_dict["node_id_1"], link_dict["node_id_2"]),
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 112, in get_link_id
    (TableEntities.Links.node_id_2 == int(node_id_2))).one().meta_id)
AttributeError: 'Links' object has no attribute 'meta_id'
2019-03-16 11:53:56,194 - ERROR - 500 POST /api/link/ (::1) 9022.84ms
2019-03-16 11:54:32,742 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 11:54:32,959 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 11:54:32,964 - DEBUG - Using selector: EpollSelector
2019-03-16 11:54:43,461 - WARNING - 400 POST /api/link/ (::1) 5580.77ms
2019-03-16 11:54:52,561 - INFO - 200 GET /api/link/ (::1) 194.13ms
2019-03-16 11:55:16,767 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 34, in post
    if "node_id" not in metadata_dict and "link_id" not in metadata_dict:
TypeError: argument of type 'bool' is not iterable
2019-03-16 11:55:16,768 - ERROR - 500 POST /api/metadata/ (::1) 1.50ms
2019-03-16 11:57:09,970 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 11:57:10,222 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 11:57:10,226 - DEBUG - Using selector: EpollSelector
2019-03-16 11:57:12,474 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 34, in post
    if ("node_id" not in metadata_dict) and ("link_id" not in metadata_dict):
TypeError: argument of type 'bool' is not iterable
2019-03-16 11:57:12,475 - ERROR - 500 POST /api/metadata/ (::1) 1.55ms
2019-03-16 11:58:11,233 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 11:58:11,512 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 11:58:11,517 - DEBUG - Using selector: EpollSelector
2019-03-16 11:58:12,489 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 34, in post
    if (("node_id" not in metadata_dict) and ("link_id" not in metadata_dict)):
TypeError: argument of type 'bool' is not iterable
2019-03-16 11:58:12,490 - ERROR - 500 POST /api/metadata/ (::1) 1.31ms
2019-03-16 11:58:18,019 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 11:58:18,254 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 11:58:18,259 - DEBUG - Using selector: EpollSelector
2019-03-16 11:58:19,027 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 34, in post
    if (("node_id" not in metadata_dict) & ("link_id" not in metadata_dict)):
TypeError: argument of type 'bool' is not iterable
2019-03-16 11:58:19,028 - ERROR - 500 POST /api/metadata/ (::1) 1.56ms
2019-03-16 12:00:27,766 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 12:00:28,019 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:00:28,024 - DEBUG - Using selector: EpollSelector
2019-03-16 12:00:31,732 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 33, in post
    test = "node_id" not in metadata_dict
TypeError: argument of type 'bool' is not iterable
2019-03-16 12:00:31,733 - ERROR - 500 POST /api/metadata/ (::1) 1.82ms
2019-03-16 12:01:10,530 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 12:01:10,785 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:01:18,826 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:01:39,838 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:01:39,843 - DEBUG - Using selector: EpollSelector
2019-03-16 12:01:42,831 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 37, in post
    test = "node_id" not in metadata_dict
TypeError: argument of type 'bool' is not iterable
2019-03-16 12:01:42,832 - ERROR - 500 POST /api/metadata/ (::1) 1.49ms
2019-03-16 12:01:55,349 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 12:01:55,606 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:01:55,611 - DEBUG - Using selector: EpollSelector
2019-03-16 12:02:26,617 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 12:02:26,855 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:02:35,378 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:02:52,486 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:02:52,490 - DEBUG - Using selector: EpollSelector
2019-03-16 12:02:54,618 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 37, in post
    if ("node_id" not in metadata_dict + "link_id" not in metadata_dict):
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
2019-03-16 12:02:54,619 - ERROR - 500 POST /api/metadata/ (::1) 1.93ms
2019-03-16 12:03:06,998 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 12:03:07,268 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:03:07,273 - DEBUG - Using selector: EpollSelector
2019-03-16 12:03:14,460 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 48, in post
    int(MetadataUtil.get_metadata_id_with_node(metadata_dict["category"],metadata_dict["node_id"])),
AttributeError: module 'utilities.meta' has no attribute 'get_metadata_id_with_node'
2019-03-16 12:03:14,463 - ERROR - 500 POST /api/metadata/ (::1) 6016.14ms
2019-03-16 12:06:28,780 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/meta.py modified; restarting server
2019-03-16 12:06:29,039 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:06:29,044 - DEBUG - Using selector: EpollSelector
2019-03-16 12:07:20,546 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py modified; restarting server
2019-03-16 12:07:20,770 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:08:02,445 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:09:08,407 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:09:08,411 - DEBUG - Using selector: EpollSelector
2019-03-16 12:09:15,938 - WARNING - 400 POST /api/metadata/ (::1) 5245.72ms
2019-03-16 12:09:31,148 - INFO - 200 GET /api/metadata/?node_id=1 (::1) 187.89ms
2019-03-16 12:10:17,187 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 42, in post
    meta_id = MetadataUtil.create_category(metadata_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 23, in create_category
    if LinkUtil.link_id_exists(metadata_dict["link_id"]) == False:
AttributeError: module 'utilities.link' has no attribute 'link_id_exists'
2019-03-16 12:10:17,188 - ERROR - 500 POST /api/metadata/ (::1) 1.20ms
2019-03-16 12:10:57,418 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/meta.py modified; restarting server
2019-03-16 12:10:57,681 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:10:57,686 - DEBUG - Using selector: EpollSelector
2019-03-16 12:11:11,692 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/meta.py modified; restarting server
2019-03-16 12:11:11,956 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:11:11,961 - DEBUG - Using selector: EpollSelector
2019-03-16 12:11:23,530 - ERROR - Uncaught exception POST /api/metadata/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/metadata/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/metadata.py", line 42, in post
    meta_id = MetadataUtil.create_category(metadata_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 45, in create_category
    session.add(TableEntities.Metadata(link_id=int(metadata_dict["node_id"]), category=metadata_dict["category"],
KeyError: 'node_id'
2019-03-16 12:11:23,534 - ERROR - 500 POST /api/metadata/ (::1) 5248.89ms
2019-03-16 12:11:45,469 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/meta.py modified; restarting server
2019-03-16 12:11:45,725 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:11:45,729 - DEBUG - Using selector: EpollSelector
2019-03-16 12:12:02,003 - INFO - 200 POST /api/metadata/ (::1) 9270.92ms
2019-03-16 12:12:08,210 - INFO - 200 GET /api/metadata/?node_id=1 (::1) 196.09ms
2019-03-16 12:12:15,073 - WARNING - 400 GET /api/metadata/ (::1) 0.42ms
2019-03-16 12:12:30,318 - INFO - 200 GET /api/metadata/?link_id=1 (::1) 196.50ms
2019-03-16 12:14:42,236 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:18:59,148 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:18:59,152 - DEBUG - Using selector: EpollSelector
2019-03-16 12:19:10,692 - ERROR - Uncaught exception POST /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 54, in create_node
    MetadataUtil.create_category(metadata_dict, torn)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 18, in create_category
    if NodeUtil.node_id_exists(metadata_dict["node_id"]) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 65, in node_id_exists
    TableEntities.Nodes.node_id == int(node_id)).count()) != 0
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Nodes'
2019-03-16 12:19:10,693 - ERROR - 500 POST /api/node/ (::1) 8543.39ms
2019-03-16 12:19:30,653 - INFO - 200 GET /api/node/ (::1) 186.66ms
2019-03-16 12:21:08,655 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/meta.py modified; restarting server
2019-03-16 12:21:08,876 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:21:08,881 - DEBUG - Using selector: EpollSelector
2019-03-16 12:21:24,353 - ERROR - Uncaught exception POST /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 54, in create_node
    MetadataUtil.create_category(metadata_dict, torn)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 18, in create_category
    if NodeUtil.node_id_exists(metadata_dict["node_id"]) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 65, in node_id_exists
    TableEntities.Nodes.node_id == int(node_id)).count()) != 0
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Nodes'
2019-03-16 12:21:24,354 - ERROR - 500 POST /api/node/ (::1) 8558.51ms
2019-03-16 12:21:55,883 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:21:56,114 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:21:56,118 - DEBUG - Using selector: EpollSelector
2019-03-16 12:22:27,517 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:22:27,521 - DEBUG - Using selector: EpollSelector
2019-03-16 12:22:56,957 - ERROR - Uncaught exception POST /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 54, in create_node
    MetadataUtil.create_type_category(metadata_dict)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 58, in create_type_category
    session.add(TableEntities.Metadata(node_id=int(metadata_dict["node_id"]), category=metadata_dict["category"],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Nodes'
2019-03-16 12:22:56,961 - ERROR - 500 POST /api/node/ (::1) 8677.44ms
2019-03-16 12:23:27,524 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:23:27,756 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:23:27,761 - DEBUG - Using selector: EpollSelector
2019-03-16 12:23:41,263 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:23:41,509 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:23:41,513 - DEBUG - Using selector: EpollSelector
2019-03-16 12:23:55,764 - ERROR - Uncaught exception POST /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 55, in create_node
    MetadataUtil.create_type_category(metadata_dict)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 60, in create_type_category
    session.commit()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 25, in escape_item
    val = encoder(val, charset, mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 33, in escape_dict
    quoted = escape_item(v, charset, mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 25, in escape_item
    val = encoder(val, charset, mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 42, in escape_sequence
    return "(" + ",".join(n) + ")"
TypeError: sequence item 0: expected str instance, dict found
2019-03-16 12:23:55,774 - ERROR - 500 POST /api/node/ (::1) 11595.59ms
2019-03-16 12:25:07,516 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/meta.py modified; restarting server
2019-03-16 12:25:07,741 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:25:07,746 - DEBUG - Using selector: EpollSelector
2019-03-16 12:25:17,321 - INFO - 200 GET /api/node/ (::1) 2692.20ms
2019-03-16 12:25:32,266 - INFO - 200 GET /api/metadata/?link_id=4 (::1) 2690.43ms
2019-03-16 12:25:39,488 - INFO - 200 GET /api/node/ (::1) 193.21ms
2019-03-16 12:25:48,920 - ERROR - Uncaught exception POST /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 55, in create_node
    MetadataUtil.create_type_category(metadata_dict)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/meta.py", line 60, in create_type_category
    session.commit()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 25, in escape_item
    val = encoder(val, charset, mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 33, in escape_dict
    quoted = escape_item(v, charset, mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 25, in escape_item
    val = encoder(val, charset, mapping)
  File "/usr/lib/python3.6/site-packages/pymysql/converters.py", line 42, in escape_sequence
    return "(" + ",".join(n) + ")"
TypeError: sequence item 0: expected str instance, dict found
2019-03-16 12:25:48,923 - ERROR - 500 POST /api/node/ (::1) 6361.47ms
2019-03-16 12:26:24,749 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:26:24,971 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:26:24,975 - DEBUG - Using selector: EpollSelector
2019-03-16 12:26:29,978 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:26:30,205 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:26:30,209 - DEBUG - Using selector: EpollSelector
2019-03-16 12:27:32,630 - INFO - 200 GET /api/type/ (::1) 2607.19ms
2019-03-16 12:27:35,197 - INFO - 200 GET /api/type/?type_id=1 (::1) 185.82ms
2019-03-16 12:27:45,212 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:27:45,435 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:27:45,439 - DEBUG - Using selector: EpollSelector
2019-03-16 12:28:08,516 - ERROR - Uncaught exception POST /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 52, in create_node
    type_name = TypeUtil.get_type(node_dict["type_id"])["data"]["type"]
TypeError: list indices must be integers or slices, not str
2019-03-16 12:28:08,517 - ERROR - 500 POST /api/node/ (::1) 8859.87ms
2019-03-16 12:28:56,942 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/node.py modified; restarting server
2019-03-16 12:28:57,164 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 12:28:57,169 - DEBUG - Using selector: EpollSelector
2019-03-16 12:29:02,245 - INFO - 200 GET /api/type/?type_id=1 (::1) 2609.31ms
2019-03-16 12:29:19,893 - INFO - 200 POST /api/node/ (::1) 12243.41ms
2019-03-16 12:29:26,923 - INFO - 200 GET /api/metadata/?link_id=4 (::1) 187.46ms
2019-03-16 12:29:30,794 - INFO - 200 GET /api/metadata/?link_id=9 (::1) 186.99ms
2019-03-16 12:29:37,783 - INFO - 200 GET /api/metadata/?node_id=9 (::1) 187.50ms
2019-03-16 12:36:09,196 - INFO - 200 POST /api/view/ (::1) 1513.58ms
2019-03-16 12:48:16,031 - INFO - 200 GET /api/node/ (::1) 190.29ms
2019-03-16 12:53:26,725 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.21ms
2019-03-16 12:53:26,730 - WARNING - 401 POST /api/node/ (127.0.0.1) 0.30ms
2019-03-16 12:55:07,156 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.22ms
2019-03-16 12:55:07,161 - WARNING - 401 POST /api/node/ (127.0.0.1) 0.28ms
2019-03-16 12:55:31,114 - INFO - 200 GET /api/node/ (::1) 187.60ms
2019-03-16 12:55:58,492 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.31ms
2019-03-16 12:55:58,499 - WARNING - 401 POST /api/node/ (127.0.0.1) 0.28ms
2019-03-16 12:57:08,713 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.26ms
2019-03-16 12:57:11,189 - INFO - 200 POST /api/node/ (127.0.0.1) 2471.40ms
2019-03-16 12:57:59,665 - INFO - 200 GET /api/node/ (::1) 186.96ms
2019-03-16 14:05:16,930 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 1.44ms
2019-03-16 14:05:19,393 - INFO - 200 POST /api/node/ (127.0.0.1) 2458.27ms
2019-03-16 14:05:58,289 - INFO - 200 GET /api/node/ (::1) 188.36ms
2019-03-16 14:06:02,680 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.25ms
2019-03-16 14:06:05,473 - ERROR - Uncaught exception DELETE /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='DELETE', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 82, in delete
    if node_dict == False or NodeUtil.delete_node(node_dict["node_id"], self) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 152, in delete_node
    LinkUtil.delete_link_with_node(node_id)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 225, in delete_link_with_node
    MetaUtil.delete_metadata_with_link(link.link_id)
AttributeError: 'result' object has no attribute 'link_id'
2019-03-16 14:06:05,475 - ERROR - 500 DELETE /api/node/ (127.0.0.1) 2793.54ms
2019-03-16 14:06:41,383 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.35ms
2019-03-16 14:06:43,833 - INFO - 200 POST /api/node/ (127.0.0.1) 2447.15ms
2019-03-16 14:06:50,351 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.34ms
2019-03-16 14:06:50,734 - ERROR - Uncaught exception DELETE /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='DELETE', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 82, in delete
    if node_dict == False or NodeUtil.delete_node(node_dict["node_id"], self) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 152, in delete_node
    LinkUtil.delete_link_with_node(node_id)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 225, in delete_link_with_node
    MetaUtil.delete_metadata_with_link(link.link_id)
AttributeError: 'result' object has no attribute 'link_id'
2019-03-16 14:06:50,735 - ERROR - 500 DELETE /api/node/ (127.0.0.1) 375.83ms
2019-03-16 14:08:53,672 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:08:54,147 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:08:54,154 - DEBUG - Using selector: EpollSelector
2019-03-16 14:08:58,397 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.29ms
2019-03-16 14:09:03,805 - ERROR - Uncaught exception DELETE /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='DELETE', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 82, in delete
    if node_dict == False or NodeUtil.delete_node(node_dict["node_id"], self) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 152, in delete_node
    LinkUtil.delete_link_with_node(node_id)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 226, in delete_link_with_node
    MetaUtil.delete_metadata_with_link(link.link_id)
AttributeError: 'result' object has no attribute 'link_id'
2019-03-16 14:09:03,806 - ERROR - 500 DELETE /api/node/ (127.0.0.1) 5405.44ms
2019-03-16 14:10:38,161 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:10:38,406 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:10:38,411 - DEBUG - Using selector: EpollSelector
2019-03-16 14:10:43,839 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.56ms
2019-03-16 14:10:49,076 - ERROR - Uncaught exception DELETE /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='DELETE', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 82, in delete
    if node_dict == False or NodeUtil.delete_node(node_dict["node_id"], self) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 152, in delete_node
    LinkUtil.delete_link_with_node(node_id)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 227, in delete_link_with_node
    MetaUtil.delete_metadata_with_link(link.link_id)
AttributeError: 'result' object has no attribute 'link_id'
2019-03-16 14:10:49,080 - ERROR - 500 DELETE /api/node/ (127.0.0.1) 5236.37ms
2019-03-16 14:11:02,498 - INFO - 200 GET /api/link/ (::1) 187.58ms
2019-03-16 14:11:33,918 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:11:34,185 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:11:34,191 - DEBUG - Using selector: EpollSelector
2019-03-16 14:11:36,198 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:11:36,461 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:11:36,466 - DEBUG - Using selector: EpollSelector
2019-03-16 14:11:39,181 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.28ms
2019-03-16 14:11:44,579 - ERROR - Uncaught exception DELETE /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='DELETE', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 82, in delete
    if node_dict == False or NodeUtil.delete_node(node_dict["node_id"], self) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 152, in delete_node
    LinkUtil.delete_link_with_node(node_id)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 227, in delete_link_with_node
    MetaUtil.delete_metadata_with_link(link.link_id)
AttributeError: 'result' object has no attribute 'link_id'
2019-03-16 14:11:44,583 - ERROR - 500 DELETE /api/node/ (127.0.0.1) 5397.54ms
2019-03-16 14:12:37,355 - ERROR - Uncaught exception POST /api/link/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/link/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/link.py", line 47, in post
    self.write({"message":"Success", "payload":link_id})
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 746, in write
    chunk = escape.json_encode(chunk)
  File "/usr/lib/python3.6/site-packages/tornado/escape.py", line 81, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Links' is not JSON serializable
2019-03-16 14:12:37,360 - ERROR - 500 POST /api/link/ (::1) 7155.64ms
2019-03-16 14:13:05,182 - INFO - 200 GET /api/link/ (::1) 193.56ms
2019-03-16 14:13:47,473 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:13:47,722 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:13:47,727 - DEBUG - Using selector: EpollSelector
2019-03-16 14:15:14,854 - ERROR - Uncaught exception DELETE /api/node/ (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='DELETE', uri='/api/node/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 82, in delete
    if node_dict == False or NodeUtil.delete_node(node_dict["node_id"], self) == False:
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 152, in delete_node
    LinkUtil.delete_link_with_node(node_id)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/link.py", line 227, in delete_link_with_node
    MetaUtil.delete_metadata_with_link(link.link_id)
AttributeError: 'result' object has no attribute 'link_id'
2019-03-16 14:15:14,855 - ERROR - 500 DELETE /api/node/ (::1) 5228.06ms
2019-03-16 14:16:02,236 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:16:02,492 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:16:02,496 - DEBUG - Using selector: EpollSelector
2019-03-16 14:16:13,531 - INFO - 200 GET /api/node/ (::1) 2713.43ms
2019-03-16 14:16:22,542 - INFO - 200 GET /api/link/ (::1) 2693.95ms
2019-03-16 14:16:28,100 - INFO - 200 GET /api/node/ (::1) 196.31ms
2019-03-16 14:16:39,229 - INFO - 200 DELETE /api/node/ (::1) 8043.12ms
2019-03-16 14:17:06,004 - INFO - /home/adam/Documents/Git/AMS-Project/src/utilities/link.py modified; restarting server
2019-03-16 14:17:06,264 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:17:06,268 - DEBUG - Using selector: EpollSelector
2019-03-16 14:17:21,007 - INFO - 200 GET /api/link/ (::1) 2706.40ms
2019-03-16 14:17:29,735 - INFO - 200 GET /api/node/ (::1) 2708.95ms
2019-03-16 14:17:49,785 - INFO - 200 POST /api/link/ (::1) 7355.96ms
2019-03-16 14:18:09,307 - INFO - 200 DELETE /api/node/ (::1) 5782.78ms
2019-03-16 14:18:41,000 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.21ms
2019-03-16 14:18:41,209 - WARNING - 404 DELETE /api/node/ (127.0.0.1) 195.18ms
2019-03-16 14:19:02,652 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.23ms
2019-03-16 14:19:07,682 - INFO - 200 POST /api/node/ (127.0.0.1) 5025.39ms
2019-03-16 14:19:13,245 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.36ms
2019-03-16 14:19:15,948 - INFO - 200 DELETE /api/node/ (127.0.0.1) 2699.23ms
2019-03-16 14:19:32,748 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.22ms
2019-03-16 14:19:32,753 - ERROR - Uncaught exception POST /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 18, in create_node
    if TypeUtil.type_id_exists(node_dict["type_id"]) == False:
TypeError: 'bool' object is not subscriptable
2019-03-16 14:19:32,754 - ERROR - 500 POST /api/node/ (127.0.0.1) 1.83ms
2019-03-16 14:19:45,164 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.21ms
2019-03-16 14:19:45,167 - ERROR - Uncaught exception POST /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 18, in create_node
    if TypeUtil.type_id_exists(node_dict["type_id"]) == False:
TypeError: 'bool' object is not subscriptable
2019-03-16 14:19:45,168 - ERROR - 500 POST /api/node/ (127.0.0.1) 0.73ms
2019-03-16 14:19:55,511 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.31ms
2019-03-16 14:19:58,028 - INFO - 200 POST /api/node/ (127.0.0.1) 2513.62ms
2019-03-16 14:20:02,177 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.34ms
2019-03-16 14:20:04,883 - INFO - 200 DELETE /api/node/ (127.0.0.1) 2703.10ms
2019-03-16 14:28:46,771 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/link.py modified; restarting server
2019-03-16 14:28:47,002 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:28:47,007 - DEBUG - Using selector: EpollSelector
2019-03-16 14:29:44,509 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/relationship.py modified; restarting server
2019-03-16 14:29:44,743 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:29:44,748 - DEBUG - Using selector: EpollSelector
2019-03-16 14:30:06,751 - INFO - /home/adam/Documents/Git/AMS-Project/src/handlers/api/user.py modified; restarting server
2019-03-16 14:30:06,987 - DEBUG - registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
2019-03-16 14:30:06,991 - DEBUG - Using selector: EpollSelector
2019-03-16 14:54:32,076 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.36ms
2019-03-16 14:54:32,080 - ERROR - Uncaught exception POST /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 18, in create_node
    if TypeUtil.type_id_exists(node_dict["type_id"]) == False:
TypeError: 'bool' object is not subscriptable
2019-03-16 14:54:32,081 - ERROR - 500 POST /api/node/ (127.0.0.1) 1.60ms
2019-03-16 14:54:36,487 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.24ms
2019-03-16 14:54:36,490 - ERROR - Uncaught exception POST /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 18, in create_node
    if TypeUtil.type_id_exists(node_dict["type_id"]) == False:
TypeError: 'bool' object is not subscriptable
2019-03-16 14:54:36,490 - ERROR - 500 POST /api/node/ (127.0.0.1) 0.75ms
2019-03-16 14:54:44,463 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.37ms
2019-03-16 14:54:44,471 - ERROR - Uncaught exception POST /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 18, in create_node
    if TypeUtil.type_id_exists(node_dict["type_id"]) == False:
TypeError: 'bool' object is not subscriptable
2019-03-16 14:54:44,471 - ERROR - 500 POST /api/node/ (127.0.0.1) 0.83ms
2019-03-16 14:55:36,008 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.24ms
2019-03-16 14:55:50,567 - INFO - 200 POST /api/node/ (127.0.0.1) 14555.20ms
2019-03-16 14:55:59,528 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.32ms
2019-03-16 14:56:01,964 - INFO - 200 POST /api/node/ (127.0.0.1) 2428.60ms
2019-03-16 14:57:44,649 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.32ms
2019-03-16 14:57:47,081 - INFO - 200 POST /api/node/ (127.0.0.1) 2428.01ms
2019-03-16 14:57:48,140 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.33ms
2019-03-16 14:57:50,578 - INFO - 200 POST /api/node/ (127.0.0.1) 2433.09ms
2019-03-16 14:59:58,177 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.32ms
2019-03-16 14:59:58,181 - ERROR - Uncaught exception POST /api/node/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:5000', method='POST', uri='/api/node/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/adam/Documents/Git/AMS-Project/src/handlers/api/node.py", line 31, in post
    node_id = NodeUtil.create_node(node_dict, self)
  File "/home/adam/Documents/Git/AMS-Project/src/utilities/node.py", line 18, in create_node
    if TypeUtil.type_id_exists(node_dict["type_id"]) == False:
TypeError: 'bool' object is not subscriptable
2019-03-16 14:59:58,181 - ERROR - 500 POST /api/node/ (127.0.0.1) 1.16ms
2019-03-16 15:00:04,865 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.31ms
2019-03-16 15:00:07,297 - INFO - 200 POST /api/node/ (127.0.0.1) 2428.29ms
2019-03-16 15:00:07,407 - INFO - 204 OPTIONS /api/node/ (127.0.0.1) 0.38ms
2019-03-16 15:00:09,843 - INFO - 200 POST /api/node/ (127.0.0.1) 2428.92ms
